exp_name: SSN

# model related
model:
  name: 'SSN'
  in_channels: 1
  out_channels: 1
  resnet: True
  norm_type: 'Group'
  mid_act: 'relu'
  out_act: 'relu'
  optimizer: 'Adam'
  weight_decay: 4e-5
  beta1: 0.9


# dataset
dataset:
  name: 'SSN_Dataset'
  hdf5_file: 'Dataset/all_base.hdf5'
  use_ao: False
  use_64_16: False
  lights_per_scene: 10


# training related
hyper_params:
  lr: 2e-4
  epochs: 1000
  workers: 48
  batch_size: 14
  save_epoch: 20

  # visualization
  vis_iter: 10     # iteration for visualization
  save_iter: 100
  n_cols: 5
  gpus:
    - 0
    - 1
  default_folder: 'weights'
  resume: False
  resume: True
  weight_file: 'latest'
